from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    CategoryListCreateView,
    CurrentUserView,
    LoginView,
    PasswordResetView,
    PriorityListCreateView,
    ProjectInvitationCreateView,
    ProjectInvitationListView,
    ProjectInvitationRespondView,
    ProjectListCreateView,
    ProjectMembershipCreateView,
    ProjectMembershipDestroyView,
    ProjectRetrieveUpdateDestroyView,
    RegisterView,
    ReportView,
    TaskFavoriteToggleView,
    TaskListCreateView,
    TaskRetrieveUpdateDestroyView,
    TimeEntryListCreateView,
    TimeEntryRetrieveUpdateDestroyView,
    TimeEntryStartView,
    TimeEntryStopView,
    UserSearchView,
)

urlpatterns = [
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("auth/user/", CurrentUserView.as_view(), name="current_user"),
    path("users/search/", UserSearchView.as_view(), name="user_search"),
    path("auth/reset-password/", PasswordResetView.as_view(), name="reset_password"),
    path("categories/", CategoryListCreateView.as_view(), name="category_list_create"),
    path("priorities/", PriorityListCreateView.as_view(), name="priority_list_create"),
    path("projects/", ProjectListCreateView.as_view(), name="project_list_create"),
    path("projects/<int:pk>/", ProjectRetrieveUpdateDestroyView.as_view(), name="project_detail"),
    path(
        "projects/<int:project_id>/memberships/<int:pk>/",
        ProjectMembershipDestroyView.as_view(),
        name="project_membership_destroy",
    ),
    path(
        "projects/<int:project_id>/memberships/",
        ProjectMembershipCreateView.as_view(),
        name="project_membership_create",
    ),
    path("projects/<int:project_id>/invite/", ProjectInvitationCreateView.as_view(), name="project_invitation_create"),
    path("invitations/", ProjectInvitationListView.as_view(), name="invitation_list"),
    path("invitations/<int:pk>/respond/", ProjectInvitationRespondView.as_view(), name="invitation_respond"),
    path("tasks/", TaskListCreateView.as_view(), name="task_list_create"),
    path(
        "tasks/<int:pk>/",
        TaskRetrieveUpdateDestroyView.as_view(),
        name="task_detail",
    ),
    path(
        "tasks/<int:pk>/favorite/",
        TaskFavoriteToggleView.as_view(),
        name="task_favorite_toggle",
    ),
    path("time-entries/", TimeEntryListCreateView.as_view(), name="time_entry_list_create"),
    path(
        "time-entries/<int:pk>/",
        TimeEntryRetrieveUpdateDestroyView.as_view(),
        name="time_entry_detail",
    ),
    path("tasks/<int:task_id>/start/", TimeEntryStartView.as_view(), name="time_entry_start"),
    path(
        "time-entries/<int:time_entry_id>/stop/",
        TimeEntryStopView.as_view(),
        name="time_entry_stop",
    ),
    path("reports/", ReportView.as_view(), name="reports"),
]
