# Generated by Django 6.0.4 on 2026-05-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_projectinvitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinvitation',
            options={},
        ),
    ]
