# Writes .env.lan at repo root for: docker compose --env-file .env.lan
# Sets DJANGO_ALLOWED_HOSTS with this PC IPv4 (fixes DisallowedHost from phone).
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path $PSScriptRoot -Parent
$OutFile = Join-Path $RepoRoot ".env.lan"

function Get-LanIPv4 {
    $skipAlias = "(?i)loopback|wsl|vethernet|virtualbox|vmware|hyper-v|bluetooth|teredo|zerotier|tailscale|npcap|vpn"
    $candidates = @(Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | Where-Object {
            $_.IPAddress -ne "127.0.0.1" -and
            $_.InterfaceAlias -notmatch $skipAlias -and
            ($_.PrefixOrigin -eq "Dhcp" -or $_.PrefixOrigin -eq "Manual" -or $_.PrefixOrigin -eq "RouterAdvertisement")
        })
    # Prefer real LAN: 192.168 / 10, then 172.16–31 except 172.27.* (common WSL host switch).
    foreach ($c in $candidates) {
        if ($c.IPAddress -match "^192\.168\.") { return $c.IPAddress }
    }
    foreach ($c in $candidates) {
        if ($c.IPAddress -match "^10\.") { return $c.IPAddress }
    }
    foreach ($c in $candidates) {
        if ($c.IPAddress -match "^172\.(1[6-9]|2[0-9]|3[0-1])\." -and $c.IPAddress -notmatch "^172\.27\.") {
            return $c.IPAddress
        }
    }
    foreach ($c in $candidates) {
        if ($c.IPAddress -match "^(192\.168\.|10\.|172\.(1[6-9]|2[0-9]|3[0-1])\.)\d") {
            return $c.IPAddress
        }
    }
    foreach ($c in $candidates) {
        if ($c.IPAddress -notmatch "^169\.254\.") {
            return $c.IPAddress
        }
    }
    return $null
}

$ip = Get-LanIPv4
if (-not $ip) {
    Write-Error "Could not detect IPv4. Copy lan-access.env.example to .env and set your IP from ipconfig."
}

$allowed = "localhost,127.0.0.1,backend,$ip"
$csrf = "http://${ip}:3000"
$content = @"
# Generated by scripts/write-lan-env.ps1 (gitignored). Run: scripts/docker-up-lan.ps1
# Or: docker compose --env-file .env.lan up --build
DJANGO_ALLOWED_HOSTS=$allowed
DJANGO_CSRF_TRUSTED_ORIGINS=$csrf
VITE_API_BASE_URL=http://localhost:8000/api
VITE_PROXY_TARGET=http://backend:8000
"@

Set-Content -Path $OutFile -Value $content -Encoding UTF8
Write-Host "Wrote $OutFile (LAN IP: $ip). On phone open: http://${ip}:3000"
